### ISSUE TITLE
tur: [GANTI DENGAN DESKRIPSI SINGKAT]

### ISSUE THREAD

**Issue by ajamil76** [shuLhan/go-tour-id#3]
Konteks: https://go-tour-id2.appspot.com/welcome/5

Ganti judul di atas dan jelaskan isu yang anda hadapi di sini, ikutkan kode jika diperlukan

**Comment by shuLhan** [comment]
Mohon dijelaskan lebih rinci isu yang anda temukan di https://go-tour-id2.appspot.com/welcome/5.

Terima kasih.
